from typing import TypedDict

from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama
from langgraph.graph import StateGraph, START, END

from resume_schema import CandidateProfile
from job_search import search_jobs
from job_schema import Job


# ============================================================
# 1. LLM
# ============================================================

llm = ChatOllama(
    model="llama3.2:latest",
    temperature=0
)


# ============================================================
# 2. STRUCTURED OUTPUT SCHEMAS
# ============================================================

class JobAnalysis(BaseModel):

    experience_required: str = Field(
        default="Unknown",
        description=(
            "Experience requirement explicitly stated "
            "in the job description"
        )
    )

    experience_level: str = Field(
        default="Unknown",
        description=(
            "One of: Fresher, Entry Level, Junior, "
            "Mid Level, Senior, Lead, Unknown"
        )
    )

    required_skills: list[str] = Field(
        default_factory=list,
        description=(
            "Important technical skills explicitly "
            "required for the job"
        )
    )

    preferred_skills: list[str] = Field(
        default_factory=list,
        description=(
            "Preferred or nice-to-have skills"
        )
    )


class JobMatch(BaseModel):

    matching_skills: list[str] = Field(
        default_factory=list,
        description=(
            "Skills the candidate actually has "
            "that match the job"
        )
    )

    missing_skills: list[str] = Field(
        default_factory=list,
        description=(
            "Important skills explicitly required "
            "by the job that the candidate lacks"
        )
    )

    recommendation: str = Field(
        default="CONSIDER",
        description=(
            "One of APPLY, CONSIDER, or SKIP"
        )
    )

    recommendation_reason: str = Field(
        default="",
        description=(
            "Short explanation for the recommendation"
        )
    )


# ============================================================
# 3. STRUCTURED LLMs
# ============================================================

analysis_llm = llm.with_structured_output(
    JobAnalysis
)

match_llm = llm.with_structured_output(
    JobMatch
)


# ============================================================
# 4. LANGGRAPH STATE
# ============================================================

class AgentState(TypedDict):

    # Candidate profile generated by resume agent
    candidate: CandidateProfile

    # Search query
    search_query: str

    # Raw jobs from Adzuna
    jobs: list[Job]

    # Jobs after AI analysis
    analyzed_jobs: list[Job]

    # Jobs after candidate matching
    matched_jobs: list[Job]


# ============================================================
# 5. HELPER
# GET CANDIDATE SKILLS
# ============================================================

def get_candidate_skills(
    candidate: CandidateProfile
) -> list[str]:

    """
    Convert the nested Skills object into
    one flat list of unique skills.
    """

    skills = candidate.skills

    all_skills = (
        skills.programming
        + skills.machine_learning
        + skills.deep_learning
        + skills.genai
        + skills.frameworks
        + skills.databases
        + skills.cloud
        + skills.devops
        + skills.data_tools
        + skills.other
    )

    unique_skills = []

    seen = set()

    for skill in all_skills:

        if not skill:
            continue

        skill = skill.strip()

        if not skill:
            continue

        normalized = normalize_skill(
            skill
        )

        if normalized not in seen:

            seen.add(
                normalized
            )

            unique_skills.append(
                skill
            )

    return unique_skills


# ============================================================
# 6. SKILL NORMALIZATION
# ============================================================

def normalize_skill(
    skill: str
) -> str:

    """
    Normalize common variations of skills
    so that equivalent skills can match.
    """

    skill = (
        skill
        .lower()
        .strip()
    )

    skill = (
        skill
        .replace("_", " ")
        .replace("/", " ")
        .replace("-", " ")
    )

    skill = " ".join(
        skill.split()
    )

    aliases = {

        "sklearn":
            "scikit learn",

        "scikit learn":
            "scikit learn",

        "scikit learn library":
            "scikit learn",

        "ml":
            "machine learning",

        "machine learning":
            "machine learning",

        "ai":
            "artificial intelligence",

        "artificial intelligence":
            "artificial intelligence",

        "gen ai":
            "generative ai",

        "genai":
            "generative ai",

        "generative ai":
            "generative ai",

        "lang chain":
            "langchain",

        "langchain":
            "langchain",

        "vector db":
            "vector database",

        "vector databases":
            "vector database",

        "vector database":
            "vector database",

        "postgres":
            "postgresql",

        "postgresql":
            "postgresql",

        "mongo":
            "mongodb",

        "mongodb":
            "mongodb",

        "k8s":
            "kubernetes",

        "kubernetes":
            "kubernetes",

    }

    return aliases.get(
        skill,
        skill
    )


# ============================================================
# 7. CHECK SKILL MATCH
# ============================================================

def skills_match(
    candidate_skill: str,
    job_skill: str
) -> bool:

    """
    Determine whether two skills are equivalent
    or sufficiently similar.
    """

    candidate = normalize_skill(
        candidate_skill
    )

    job = normalize_skill(
        job_skill
    )

    # Exact match
    if candidate == job:
        return True

    # One contains the other
    if (
        candidate in job
        or job in candidate
    ):
        return True

    # Common mappings
    related_groups = [

        {
            "python",
            "python programming"
        },

        {
            "machine learning",
            "machine learning algorithms",
            "machine learning models"
        },

        {
            "deep learning",
            "deep learning models"
        },

        {
            "scikit learn",
            "scikit learn library"
        },

        {
            "pytorch",
            "torch"
        },

        {
            "tensorflow",
            "tensorflow keras"
        },

        {
            "generative ai",
            "genai",
            "generative artificial intelligence"
        },

        {
            "natural language processing",
            "nlp"
        },

        {
            "postgresql",
            "postgres"
        },

        {
            "mongodb",
            "mongo"
        },

        {
            "kubernetes",
            "k8s"
        },

    ]

    for group in related_groups:

        if (
            candidate in group
            and job in group
        ):

            return True

    return False


# ============================================================
# 8. GET EDUCATION
# ============================================================

def get_candidate_education(
    candidate: CandidateProfile
) -> str:

    education_list = []

    for education in candidate.education:

        parts = []

        if education.degree:

            parts.append(
                education.degree
            )

        if education.field_of_study:

            parts.append(
                education.field_of_study
            )

        if education.institution:

            parts.append(
                education.institution
            )

        if education.graduation_year:

            parts.append(
                education.graduation_year
            )

        if education.grade:

            parts.append(
                education.grade
            )

        if parts:

            education_list.append(
                " - ".join(parts)
            )

    if not education_list:

        return "Not available"

    return "\n".join(
        education_list
    )


# ============================================================
# 9. GET EXPERIENCE
# ============================================================

def get_candidate_experience(
    candidate: CandidateProfile
) -> str:

    experience_list = []

    for experience in candidate.experience:

        parts = []

        if experience.role:

            parts.append(
                experience.role
            )

        if experience.company:

            parts.append(
                experience.company
            )

        if experience.location:

            parts.append(
                experience.location
            )

        if experience.duration:

            parts.append(
                experience.duration
            )

        if experience.responsibilities:

            parts.append(
                "Responsibilities: "
                + "; ".join(
                    experience.responsibilities
                )
            )

        if parts:

            experience_list.append(
                " | ".join(parts)
            )

    if not experience_list:

        return (
            "No professional experience "
            "listed in the resume."
        )

    return "\n".join(
        experience_list
    )


# ============================================================
# 10. GET PROJECTS
# ============================================================

def get_candidate_projects(
    candidate: CandidateProfile
) -> str:

    project_list = []

    for project in candidate.projects:

        parts = []

        if project.name:

            parts.append(
                project.name
            )

        if project.description:

            parts.append(
                project.description
            )

        if project.technologies:

            parts.append(
                "Technologies: "
                + ", ".join(
                    project.technologies
                )
            )

        if parts:

            project_list.append(
                " - ".join(parts)
            )

    if not project_list:

        return "No projects listed."

    return "\n".join(
        project_list
    )


# ============================================================
# 11. CALCULATE SKILL MATCHES
# ============================================================

def calculate_skill_matches(
    candidate_skills: list[str],
    job_skills: list[str]
) -> list[str]:

    matches = []

    for job_skill in job_skills:

        for candidate_skill in candidate_skills:

            if skills_match(
                candidate_skill,
                job_skill
            ):

                if job_skill not in matches:

                    matches.append(
                        job_skill
                    )

                break

    return matches


# ============================================================
# 12. CALCULATE MISSING SKILLS
# ============================================================

def calculate_missing_skills(
    candidate_skills: list[str],
    required_skills: list[str]
) -> list[str]:

    missing = []

    for required_skill in required_skills:

        found = False

        for candidate_skill in candidate_skills:

            if skills_match(
                candidate_skill,
                required_skill
            ):

                found = True
                break

        if not found:

            if required_skill not in missing:

                missing.append(
                    required_skill
                )

    return missing


# ============================================================
# 13. CALCULATE MATCH SCORE
# ============================================================

def calculate_match_score(
    candidate: CandidateProfile,
    job: Job
) -> float:

    """
    Calculate the numerical job match score
    using deterministic Python logic.

    Score:

    Required skills  : 50
    Preferred skills : 15
    Experience       : 15
    Role relevance   : 10
    Projects/Edu     : 10
    """

    candidate_skills = (
        get_candidate_skills(
            candidate
        )
    )

    required_skills = (
        job.required_skills
    )

    preferred_skills = (
        job.preferred_skills
    )


    # ========================================================
    # REQUIRED SKILLS — 50 POINTS
    # ========================================================

    if required_skills:

        required_matches = (
            calculate_skill_matches(
                candidate_skills,
                required_skills
            )
        )

        required_score = (
            len(required_matches)
            / len(required_skills)
        ) * 50

    else:

        required_score = 25


    # ========================================================
    # PREFERRED SKILLS — 15 POINTS
    # ========================================================

    if preferred_skills:

        preferred_matches = (
            calculate_skill_matches(
                candidate_skills,
                preferred_skills
            )
        )

        preferred_score = (
            len(preferred_matches)
            / len(preferred_skills)
        ) * 15

    else:

        preferred_score = 7.5


    # ========================================================
    # EXPERIENCE — 15 POINTS
    # ========================================================

    level = (
        job.experience_level
        or "Unknown"
    ).lower()

    experience_text = (
        job.experience_required
        or ""
    ).lower()

    candidate_has_experience = (
        len(candidate.experience) > 0
    )


    # Fresher / entry-level
    if any(
        keyword in level
        for keyword in [
            "fresher",
            "entry level",
            "junior",
            "graduate",
            "trainee"
        ]
    ):

        experience_score = 15


    # Senior / Lead without experience
    elif any(
        keyword in level
        for keyword in [
            "senior",
            "lead"
        ]
    ):

        if candidate_has_experience:

            experience_score = 15

        else:

            experience_score = 0


    # Unknown
    elif (
        not experience_text
        or experience_text == "unknown"
    ):

        experience_score = 10


    # Mid-level
    elif candidate_has_experience:

        experience_score = 15

    else:

        experience_score = 3


    # ========================================================
    # ROLE RELEVANCE — 10 POINTS
    # ========================================================

    target_roles = [
        normalize_skill(role)
        for role in candidate.target_roles
        if role
    ]

    job_title = normalize_skill(
        job.title
    )

    role_score = 0


    for role in target_roles:

        if (
            role in job_title
            or job_title in role
        ):

            role_score = 10

            break


    # Generic AI/ML relevance
    if role_score == 0:

        role_keywords = [

            "machine learning",

            "artificial intelligence",

            "ai engineer",

            "machine learning engineer",

            "ml engineer",

            "data scientist",

            "data science",

            "generative ai",

            "genai",

        ]

        if any(
            keyword in job_title
            for keyword in role_keywords
        ):

            role_score = 7

        else:

            role_score = 3


    # ========================================================
    # PROJECT / EDUCATION — 10 POINTS
    # ========================================================

    if candidate.projects:

        project_score = 10

    elif candidate.education:

        project_score = 7

    else:

        project_score = 3


    # ========================================================
    # FINAL SCORE
    # ========================================================

    score = (
        required_score
        + preferred_score
        + experience_score
        + role_score
        + project_score
    )


    # Clamp score
    score = max(
        0.0,
        min(
            100.0,
            score
        )
    )


    return round(
        score,
        1
    )


# ============================================================
# 14. SEARCH JOBS NODE
# ============================================================

def search_node(
    state: AgentState
):

    print(
        "\n🔎 Searching jobs..."
    )

    candidate = state[
        "candidate"
    ]

    search_query = state[
        "search_query"
    ]


    # --------------------------------------------------------
    # Candidate location
    # --------------------------------------------------------

    location = (
        candidate
        .personal_info
        .location
        or "India"
    )


    print(
        f"Query    : {search_query}"
    )

    print(
        f"Location : {location}"
    )


    # --------------------------------------------------------
    # Call Adzuna
    # --------------------------------------------------------

    try:

        jobs = search_jobs(

            query=search_query,

            location=location,

            country="in",

            results_per_page=10
        )

    except Exception as e:

        print(
            f"❌ Job search failed: {e}"
        )

        return {
            "jobs": []
        }


    # --------------------------------------------------------
    # Remove duplicates
    # --------------------------------------------------------

    unique_jobs = []

    seen = set()

    for job in jobs:

        if job.url:

            key = (
                job.url
                .lower()
                .strip()
            )

        else:

            key = (
                f"{job.title.lower()}|"
                f"{job.company.lower()}|"
                f"{job.location.lower()}"
            )

        if key not in seen:

            seen.add(
                key
            )

            unique_jobs.append(
                job
            )


    print(
        f"Found {len(unique_jobs)} unique jobs"
    )


    return {
        "jobs": unique_jobs
    }


# ============================================================
# 15. ANALYZE JOBS NODE
# ============================================================

def analyze_jobs_node(
    state: AgentState
):

    print(
        "\n🧠 Analyzing job requirements..."
    )

    analyzed_jobs = []

    jobs = state[
        "jobs"
    ]


    for i, job in enumerate(
        jobs,
        start=1
    ):

        print(
            f"Analyzing {i}/{len(jobs)}: "
            f"{job.title} - {job.company}"
        )


        description = (
            job.description
            or ""
        )


        # ----------------------------------------------------
        # Fallback
        # ----------------------------------------------------

        if not description.strip():

            description = f"""
Job Title:
{job.title}

Company:
{job.company}

Location:
{job.location}

Employment Type:
{job.employment_type}

Salary:
{job.salary}
"""


        # ----------------------------------------------------
        # Prompt
        # ----------------------------------------------------

        prompt = f"""
You are an expert technical recruiter.

Analyze the following job posting.

============================================================
JOB
============================================================

Title:
{job.title}

Company:
{job.company}

Location:
{job.location}

Employment Type:
{job.employment_type}

Salary:
{job.salary}

Description:
{description}


============================================================
EXTRACT
============================================================

Extract:

1. Required experience.
2. Experience level.
3. Required technical skills.
4. Preferred technical skills.


Experience level must be exactly one of:

Fresher
Entry Level
Junior
Mid Level
Senior
Lead
Unknown


============================================================
RULES
============================================================

- Only extract information explicitly present.
- Never invent skills.
- Never invent experience requirements.
- Do not assume seniority from salary.
- Separate required skills from preferred skills.
- Do not treat every technology mentioned in the
  description as a required skill.
- Responsibilities are not automatically skills.
- Do not convert generic words such as "performance",
  "reliability", or "communication" into technical skills.
- Focus on genuine job requirements.
"""


        try:

            result = analysis_llm.invoke(
                prompt
            )


            job.experience_required = (
                result.experience_required
            )

            job.experience_level = (
                result.experience_level
            )

            job.required_skills = (
                result.required_skills
            )

            job.preferred_skills = (
                result.preferred_skills
            )


            analyzed_jobs.append(
                job
            )


        except Exception as e:

            print(
                f"⚠️ Analysis failed: {e}"
            )

            analyzed_jobs.append(
                job
            )


    return {
        "analyzed_jobs":
            analyzed_jobs
    }


# ============================================================
# 16. MATCH JOBS NODE
# ============================================================

def match_jobs_node(
    state: AgentState
):

    print(
        "\n🎯 Matching jobs against candidate profile..."
    )

    candidate = state[
        "candidate"
    ]

    matched_jobs = []


    # --------------------------------------------------------
    # Candidate information
    # --------------------------------------------------------

    candidate_name = (
        candidate
        .personal_info
        .name
        or "Candidate"
    )


    candidate_location = (
        candidate
        .personal_info
        .location
        or "Not specified"
    )


    candidate_skills = (
        get_candidate_skills(
            candidate
        )
    )


    candidate_education = (
        get_candidate_education(
            candidate
        )
    )


    candidate_experience = (
        get_candidate_experience(
            candidate
        )
    )


    candidate_projects = (
        get_candidate_projects(
            candidate
        )
    )


    candidate_roles = (
        candidate.target_roles
        if candidate.target_roles
        else []
    )


    # --------------------------------------------------------
    # Match every job
    # --------------------------------------------------------

    jobs = state[
        "analyzed_jobs"
    ]


    for i, job in enumerate(
        jobs,
        start=1
    ):

        print(
            f"Matching {i}/{len(jobs)}: "
            f"{job.title} - {job.company}"
        )


        # ====================================================
        # PYTHON SKILL CALCULATION
        # ====================================================

        calculated_matching_skills = (
            calculate_skill_matches(
                candidate_skills,
                job.required_skills
                + job.preferred_skills
            )
        )


        calculated_missing_skills = (
            calculate_missing_skills(
                candidate_skills,
                job.required_skills
            )
        )


        # ====================================================
        # PYTHON SCORE
        # ====================================================

        score = calculate_match_score(
            candidate,
            job
        )


        # ====================================================
        # LLM MATCHING
        # ====================================================

        prompt = f"""
You are a professional AI job-matching assistant.

Compare the candidate with ONE job.

============================================================
CANDIDATE
============================================================

Name:
{candidate_name}

Location:
{candidate_location}

Education:
{candidate_education}

Professional Experience:
{candidate_experience}

Skills:
{candidate_skills}

Target Roles:
{candidate_roles}

Projects:
{candidate_projects}


============================================================
JOB
============================================================

Title:
{job.title}

Company:
{job.company}

Location:
{job.location}

Experience Required:
{job.experience_required}

Experience Level:
{job.experience_level}

Required Skills:
{job.required_skills}

Preferred Skills:
{job.preferred_skills}

Description:
{job.description or "Not available"}


============================================================
MATCHING TASK
============================================================

Identify:

1. Matching skills.
2. Missing important required skills.
3. Recommendation.
4. Short reason.


============================================================
IMPORTANT RULES
============================================================

- Only identify skills the candidate actually has.
- Do not invent candidate skills.
- Do not list every candidate skill as a missing skill.
- Only mark skills as missing if they are required by
  the job and are not present in the candidate profile.
- Preferred skills are NOT required skills.
- Consider equivalent names such as:
  Python = Python programming
  ML = Machine Learning
  GenAI = Generative AI
  Scikit Learn = scikit-learn
  Lang Chain = LangChain
  K8s = Kubernetes

Experience rules:

- Fresher, Graduate, Entry Level, Junior and Trainee
  positions can be recommended to candidates without
  professional experience.

- Senior and Lead positions should generally be SKIP
  for candidates without professional experience.

Recommendation must be exactly one of:

APPLY
CONSIDER
SKIP


APPLY:
Strong realistic fit.

CONSIDER:
Reasonable fit but meaningful gaps exist.

SKIP:
Major mismatch or unsuitable experience level.
"""


        try:

            result = match_llm.invoke(
                prompt
            )


            # =================================================
            # USE PYTHON-CALCULATED SKILLS
            # =================================================

            if calculated_matching_skills:

                job.matching_skills = (
                    calculated_matching_skills
                )

            else:

                job.matching_skills = (
                    result.matching_skills
                )


            if calculated_missing_skills:

                job.missing_skills = (
                    calculated_missing_skills
                )

            else:

                job.missing_skills = []


            # =================================================
            # SCORE
            # =================================================

            job.match_score = (
                score
            )


            # =================================================
            # RECOMMENDATION
            # =================================================

            recommendation = (
                result.recommendation
                .strip()
                .upper()
            )


            # -------------------------------------------------
            # Hard rule for senior jobs
            # -------------------------------------------------

            level = (
                job.experience_level
                or ""
            ).lower()


            candidate_has_experience = (
                len(candidate.experience) > 0
            )


            if (
                not candidate_has_experience
                and (
                    "senior" in level
                    or "lead" in level
                )
            ):

                recommendation = "SKIP"


            if recommendation not in {
                "APPLY",
                "CONSIDER",
                "SKIP"
            }:

                recommendation = (
                    "CONSIDER"
                )


            job.recommendation = (
                recommendation
            )


            # =================================================
            # REASON
            # =================================================

            reason = (
                result.recommendation_reason
                or ""
            ).strip()


            if not reason:

                reason = (
                    "Match evaluated using "
                    "skills, experience, role relevance, "
                    "education and projects."
                )


            job.recommendation_reason = (
                reason
            )


            matched_jobs.append(
                job
            )


        except Exception as e:

            print(
                f"⚠️ Matching failed: {e}"
            )


            # ------------------------------------------------
            # Still preserve Python score
            # ------------------------------------------------

            job.match_score = (
                score
            )


            job.matching_skills = (
                calculated_matching_skills
            )


            job.missing_skills = (
                calculated_missing_skills
            )


            job.recommendation = (
                "CONSIDER"
            )


            job.recommendation_reason = (
                "AI explanation failed, "
                "but the job was scored using "
                "the deterministic matching system."
            )


            matched_jobs.append(
                job
            )


    return {
        "matched_jobs":
            matched_jobs
    }


# ============================================================
# 17. RANKING NODE
# ============================================================

def rank_jobs_node(
    state: AgentState
):

    print(
        "\n📊 Ranking jobs..."
    )


    jobs = state[
        "matched_jobs"
    ]


    # --------------------------------------------------------
    # Ranking
    # --------------------------------------------------------

    jobs.sort(
        key=lambda job: job.match_score,
        reverse=True
    )


    return {
        "matched_jobs": jobs
    }


# ============================================================
# 18. BUILD LANGGRAPH
# ============================================================

graph = StateGraph(
    AgentState
)


# ============================================================
# 19. ADD NODES
# ============================================================

graph.add_node(
    "search",
    search_node
)

graph.add_node(
    "analyze",
    analyze_jobs_node
)

graph.add_node(
    "match",
    match_jobs_node
)

graph.add_node(
    "rank",
    rank_jobs_node
)


# ============================================================
# 20. ADD EDGES
# ============================================================

graph.add_edge(
    START,
    "search"
)

graph.add_edge(
    "search",
    "analyze"
)

graph.add_edge(
    "analyze",
    "match"
)

graph.add_edge(
    "match",
    "rank"
)

graph.add_edge(
    "rank",
    END
)


# ============================================================
# 21. COMPILE
# ============================================================

app = graph.compile()


# ============================================================
# 22. PUBLIC GRAPH
# ============================================================

job_discovery_graph = app